PREFIX apf: <http://jena.apache.org/ARQ/property#>
PREFIX fx: <http://sparql.xyz/facade-x/ns/>
PREFIX gn: <https://www.geonames.org/ontology#>
PREFIX xyz: <http://sparql.xyz/facade-x/data/>
PREFIX xsd: <http://www.w3.org/2001/XMLSchema#>
PREFIX wgs84_pos: <http://www.w3.org/2003/01/geo/wgs84_pos#>
PREFIX rdfs: <http://www.w3.org/1999/02/22-rdf-syntax-ns#>

CONSTRUCT {
    ?adm1Uri gn:admin1Code ?adm1Code .
    ?adm2Uri gn:admin2Code ?adm2Code .
    ?adm3Uri gn:admin3Code ?adm3Code .
    ?adm4Uri gn:admin4Code ?adm4Code .
}
WHERE {
    {
        SERVICE <x-sparql-anything:> {
            fx:properties fx:location "data/admin1-codes.csv" ;
                fx:csv.delimiter "\t" ;
                fx:csv.headers true ;
            .
            [
                xyz:admin1code ?adm1Code ;
                xyz:geonameId ?adm1Id ;
            ]
            BIND(URI(CONCAT("https://sws.geonames.org/", ?adm1Id, "/")) as ?adm1Uri)
        }
    }
    UNION {
        SERVICE <x-sparql-anything:> {
            fx:properties fx:location "data/admin2-codes.csv" ;
                fx:csv.delimiter "\t" ;
                fx:csv.headers true ;
            .
            [
                xyz:admin2code ?adm2Code ;
                xyz:geonameId ?adm2Id ;
            ]
            BIND(URI(CONCAT("https://sws.geonames.org/", ?adm2Id, "/")) as ?adm2Uri)
        }
    }
    UNION {
        SERVICE <x-sparql-anything:> {
            fx:properties fx:location "data/admin3-codes.csv" ;
                fx:csv.delimiter "\t" ;
                fx:csv.headers true ;
            .
            [
                xyz:admin3code ?adm3Code ;
                xyz:geonameId ?adm3Id ;
            ]
            BIND(URI(CONCAT("https://sws.geonames.org/", ?adm3Id, "/")) as ?adm3Uri)
        }
    }
    UNION {
        SERVICE <x-sparql-anything:> {
            fx:properties fx:location "data/admin4-codes.csv" ;
                fx:csv.delimiter "\t" ;
                fx:csv.headers true ;
            .
            [
                xyz:admin4code ?adm4Code ;
                xyz:geonameId ?adm4Id ;
            ]
            BIND(URI(CONCAT("https://sws.geonames.org/", ?adm4Id, "/")) as ?adm4Uri)
        }
    }
}