PREFIX apf: <http://jena.apache.org/ARQ/property#>
PREFIX fx: <http://sparql.xyz/facade-x/ns/>
PREFIX gn: <https://www.geonames.org/ontology#>
PREFIX xyz: <http://sparql.xyz/facade-x/data/>
PREFIX xsd: <http://www.w3.org/2001/XMLSchema#>
PREFIX wgs84_pos: <http://www.w3.org/2003/01/geo/wgs84_pos#>
PREFIX rdfs: <http://www.w3.org/1999/02/22-rdf-syntax-ns#>

CONSTRUCT {
    ?countryUri xyz:countryId ?countryId .
    ?countryUri xyz:countryCode ?countryCode .
    ?countryUri xyz:name ?countryName .

    ?adm1Uri xyz:admin1code ?adm1code .
    ?adm2Uri xyz:admin2code ?adm2code .
    ?adm3Uri xyz:admin3code ?adm3code .
    ?adm4Uri xyz:admin4code ?adm4code .
}
WHERE {
    {
        SERVICE <x-sparql-anything:> {
            fx:properties fx:location "data/country-codes.csv" ;
                fx:csv.delimiter "\t" ;
                fx:csv.headers true ;
            .
            [
                xyz:countryId ?countryId ;
                xyz:countryCode ?countryCode ;
                xyz:name ?countryName ;
            ]
            BIND(URI(CONCAT("https://sws.geonames.org/", ?countryId, "/")) AS ?countryUri)
        }
    }
    UNION {
        SERVICE <x-sparql-anything:> {
            fx:properties fx:location "data/admin1-codes.csv" ;
                fx:csv.delimiter "\t" ;
                fx:csv.headers true ;
            .
            [
                xyz:admin1code ?adm1code ;
                xyz:geonameId ?adm1Id ;
            ]
            BIND(URI(CONCAT("https://sws.geonames.org/", ?adm1Id, "/")) AS ?adm1Uri)
        }
    }
    UNION {
        SERVICE <x-sparql-anything:> {
            fx:properties fx:location "data/admin2-codes.csv" ;
                fx:csv.delimiter "\t" ;
                fx:csv.headers true ;
            .
            [
                xyz:admin2code ?adm2code ;
                xyz:geonameId ?adm2Id ;
            ]
            BIND(URI(CONCAT("https://sws.geonames.org/", ?adm2Id, "/")) AS ?adm2Uri)
        }
    }
    UNION {
        SERVICE <x-sparql-anything:> {
            fx:properties fx:location "data/admin3-codes.csv" ;
                fx:csv.delimiter "\t" ;
                fx:csv.headers true ;
            .
            [
                xyz:admin3code ?adm3code ;
                xyz:geonameId ?adm3Id ;
            ]
            BIND(URI(CONCAT("https://sws.geonames.org/", ?adm3Id, "/")) AS ?adm3Uri)
        }
    }
    UNION {
        SERVICE <x-sparql-anything:> {
            fx:properties fx:location "data/admin4-codes.csv" ;
                fx:csv.delimiter "\t" ;
                fx:csv.headers true ;
            .
            [
                xyz:admin4code ?adm4code ;
                xyz:geonameId ?adm4Id ;
            ]
            BIND(URI(CONCAT("https://sws.geonames.org/", ?adm4Id, "/")) AS ?adm4Uri)
        }
    }
}
